port: 7880
bind_addresses:
  - 0.0.0.0
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: false
  node_ip: 172.25.10.142
keys:
  trustnow-livekit-key: aca5168faae6ea15ed85e0a0d80d14c1dd5f19bbc97d996dbe2231a3a6bc23ff
logging:
  level: info
  pion_level: error
room:
  auto_create: true
  empty_timeout: 300
  departure_timeout: 20
