-- ═══════════════════════════════════════════════════════════════
-- TRUSTNOW GLOBAL VOICE LIBRARY — CONTACT CENTRE EDITION
-- Sources: ElevenLabs pre-made voices + TRUSTNOW-designed voices
-- All voices tested for contact centre use
-- All use eleven_flash_v2_5 model for realtime synthesis
-- ═══════════════════════════════════════════════════════════════

-- English US
INSERT INTO voices (voice_id, tenant_id, is_global, provider, source_type, name, description, gender, age_group, accent, language_tags, trait_tags, tone_tags, use_case_tags, emotion_range, elevenlabs_voice_id, elevenlabs_model, stability_default, similarity_default, speed_default) VALUES
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'elevenlabs_premade', 'Sarah (EN-US)', 'Warm, professional American female voice. Clear enunciation, reassuring tone. Ideal for banking, healthcare, and insurance contact centres.', 'female', 'young', 'American', ARRAY['en'], ARRAY['warm','clear','professional'], ARRAY['professional','warm'], ARRAY['customer_service','banking','healthcare'], 'moderate', 'EXAVITQu4vr4xnSDxMaL', 'eleven_flash_v2_5', 0.65, 0.75, 1.0),
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'elevenlabs_premade', 'Michael (EN-US)', 'Authoritative, trustworthy American male voice. Confident delivery with natural warmth. Perfect for financial services and enterprise support.', 'male', 'middle_aged', 'American', ARRAY['en'], ARRAY['authoritative','trustworthy','confident'], ARRAY['authoritative','professional'], ARRAY['customer_service','financial_services','technical_support'], 'limited', 'flq6f7yk4E4fJM5XTYuZ', 'eleven_flash_v2_5', 0.70, 0.75, 1.0),
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'elevenlabs_premade', 'Jessica (EN-US)', 'Energetic, empathetic American female. High emotional range — excellent for de-escalation and complex complaint handling.', 'female', 'young', 'American', ARRAY['en'], ARRAY['empathetic','energetic','expressive'], ARRAY['friendly','warm'], ARRAY['customer_service','complaint_handling','healthcare'], 'expressive', 'cgSgspJ2msm6clMCkdW9', 'eleven_flash_v2_5', 0.50, 0.75, 1.0),
-- English UK
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'elevenlabs_premade', 'Charlotte (EN-GB)', 'Polished, composed British female voice. Professional gravitas with friendly undertones. Ideal for premium customer service tiers.', 'female', 'middle_aged', 'British', ARRAY['en'], ARRAY['polished','composed','professional'], ARRAY['authoritative','professional'], ARRAY['customer_service','premium_banking','insurance'], 'moderate', 'XB0fDUnXU5powFXDhCwa', 'eleven_flash_v2_5', 0.70, 0.75, 1.0),
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'elevenlabs_premade', 'James (EN-GB)', 'Deep, reassuring British male voice. Commands confidence without being intimidating. Strong for regulated industries.', 'male', 'middle_aged', 'British', ARRAY['en'], ARRAY['deep','reassuring','confident'], ARRAY['authoritative','warm'], ARRAY['customer_service','banking','legal'], 'limited', 'ZQe5CZNOzWyzPSCn5a3c', 'eleven_flash_v2_5', 0.75, 0.75, 0.95),
-- English Australian
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'elevenlabs_premade', 'Emma (EN-AU)', 'Friendly, approachable Australian female. Natural conversational flow, high relatability. Ideal for telco and retail.', 'female', 'young', 'Australian', ARRAY['en'], ARRAY['friendly','approachable','natural'], ARRAY['friendly','warm'], ARRAY['customer_service','telco','retail'], 'moderate', 'pFZP5JQG7iQjIQuC4Bku', 'eleven_flash_v2_5', 0.60, 0.75, 1.05),
-- English Indian
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Priya (EN-IN)', 'Professional Indian English female voice. Clear, neutral accent with warm delivery. Designed specifically for BPO operations.', 'female', 'young', 'Indian', ARRAY['en'], ARRAY['professional','clear','warm'], ARRAY['professional','warm'], ARRAY['customer_service','bpo','technical_support'], 'moderate', NULL, 'eleven_flash_v2_5', 0.65, 0.75, 1.0),
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Arjun (EN-IN)', 'Confident Indian English male voice. Technical clarity, professional tone. Excellent for IT support and provisioning workflows.', 'male', 'young', 'Indian', ARRAY['en'], ARRAY['confident','clear','technical'], ARRAY['professional','authoritative'], ARRAY['technical_support','bpo','provisioning'], 'limited', NULL, 'eleven_flash_v2_5', 0.70, 0.75, 1.0),
-- Spanish
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'elevenlabs_premade', 'Sofia (ES-ES)', 'Natural Castilian Spanish female. Warm, professional delivery. Clear pronunciation suitable for all Spanish-speaking markets.', 'female', 'young', 'Castilian', ARRAY['es'], ARRAY['warm','clear','professional'], ARRAY['professional','warm'], ARRAY['customer_service','banking','insurance'], 'moderate', 'AZnzlk1XvdvUeBnXmlld', 'eleven_flash_v2_5', 0.65, 0.75, 1.0),
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'elevenlabs_premade', 'Carlos (ES-MX)', 'Mexican Spanish male voice. Friendly, approachable delivery with neutral LatAm accent. Ideal for pan-Latin American deployments.', 'male', 'middle_aged', 'Latin American', ARRAY['es'], ARRAY['friendly','neutral','professional'], ARRAY['friendly','professional'], ARRAY['customer_service','telco','retail'], 'moderate', 'VR6AewLTigWG4xSOukaG', 'eleven_flash_v2_5', 0.65, 0.75, 1.0),
-- Portuguese
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'elevenlabs_premade', 'Ana (PT-BR)', 'Brazilian Portuguese female. Natural, energetic delivery. High relatability for consumer-facing applications.', 'female', 'young', 'Brazilian', ARRAY['pt'], ARRAY['natural','energetic','friendly'], ARRAY['friendly','warm'], ARRAY['customer_service','retail','telco'], 'expressive', 'ODq5zmih8GrVes37Dizd', 'eleven_flash_v2_5', 0.55, 0.75, 1.05),
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'elevenlabs_premade', 'Ricardo (PT-PT)', 'European Portuguese male. Composed, professional delivery. Suitable for formal service contexts.', 'male', 'middle_aged', 'European', ARRAY['pt'], ARRAY['composed','professional','clear'], ARRAY['professional','authoritative'], ARRAY['customer_service','banking','insurance'], 'limited', 'SOYHLrjzK2X1ezoPC6cr', 'eleven_flash_v2_5', 0.70, 0.75, 0.95),
-- French
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'elevenlabs_premade', 'Camille (FR-FR)', 'Native Parisian French female. Elegant, professional tone. Ideal for premium services.', 'female', 'young', 'Parisian', ARRAY['fr'], ARRAY['elegant','professional','clear'], ARRAY['professional','warm'], ARRAY['customer_service','banking','premium'], 'moderate', 'CwhRBWXzGAHq8TQ4Fs17', 'eleven_flash_v2_5', 0.65, 0.75, 1.0),
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'elevenlabs_premade', 'Marc (FR-FR)', 'Confident French male voice. Clear diction, authoritative but approachable. Strong for financial and telco.', 'male', 'middle_aged', 'Parisian', ARRAY['fr'], ARRAY['confident','clear','authoritative'], ARRAY['authoritative','professional'], ARRAY['customer_service','banking','telco'], 'limited', 'onwK4e9ZLuTAKqWW03F9', 'eleven_flash_v2_5', 0.70, 0.75, 0.95),
-- German
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'elevenlabs_premade', 'Lena (DE)', 'Professional German female. Clear, precise delivery with natural warmth. Ideal for B2B and enterprise contact centres.', 'female', 'middle_aged', 'Standard German', ARRAY['de'], ARRAY['precise','professional','warm'], ARRAY['professional','authoritative'], ARRAY['customer_service','b2b','enterprise_support'], 'moderate', 'MF3mGyEYCl7XYWbV9V6O', 'eleven_flash_v2_5', 0.70, 0.75, 1.0),
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'elevenlabs_premade', 'Klaus (DE)', 'Deep, composed German male voice. Trustworthy and measured. Strong for financial services.', 'male', 'middle_aged', 'Standard German', ARRAY['de'], ARRAY['deep','composed','trustworthy'], ARRAY['authoritative','professional'], ARRAY['customer_service','banking','insurance'], 'limited', 'TxGEqnHWrfWFTfGW9XjX', 'eleven_flash_v2_5', 0.75, 0.75, 0.95),
-- Arabic
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Layla (AR-SA)', 'Professional Modern Standard Arabic female. Clear, authoritative delivery suitable for Gulf markets. Formal register.', 'female', 'middle_aged', 'Gulf/MSA', ARRAY['ar'], ARRAY['professional','clear','formal'], ARRAY['professional','authoritative'], ARRAY['customer_service','banking','government'], 'limited', NULL, 'eleven_flash_v2_5', 0.70, 0.75, 0.95),
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Omar (AR-SA)', 'Confident Arabic male voice. Composed, respectful tone. Ideal for banking and government services in the Gulf.', 'male', 'middle_aged', 'Gulf/MSA', ARRAY['ar'], ARRAY['confident','respectful','professional'], ARRAY['authoritative','professional'], ARRAY['customer_service','banking','government'], 'limited', NULL, 'eleven_flash_v2_5', 0.70, 0.75, 0.95),
-- Hindi
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Ananya (HI)', 'Warm, professional Hindi female voice. Natural conversational flow. Designed for Indian contact centre operations.', 'female', 'young', 'Standard Hindi', ARRAY['hi'], ARRAY['warm','natural','professional'], ARRAY['warm','professional'], ARRAY['customer_service','banking','telco'], 'moderate', NULL, 'eleven_flash_v2_5', 0.65, 0.75, 1.0),
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Vikram (HI)', 'Clear, authoritative Hindi male voice. Professional register suitable for financial and utility services.', 'male', 'middle_aged', 'Standard Hindi', ARRAY['hi'], ARRAY['clear','authoritative','professional'], ARRAY['authoritative','professional'], ARRAY['customer_service','banking','utilities'], 'limited', NULL, 'eleven_flash_v2_5', 0.70, 0.75, 0.95),
-- Mandarin Chinese
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Mei (ZH)', 'Professional Mandarin female voice. Neutral Beijing standard pronunciation. Suitable for mainland China and Taiwan markets.', 'female', 'young', 'Mandarin/Putonghua', ARRAY['zh'], ARRAY['professional','neutral','clear'], ARRAY['professional','warm'], ARRAY['customer_service','banking','e_commerce'], 'moderate', NULL, 'eleven_flash_v2_5', 0.65, 0.75, 1.0),
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Wei (ZH)', 'Composed Mandarin male voice. Professional tone with authoritative delivery. Enterprise-grade.', 'male', 'middle_aged', 'Mandarin/Putonghua', ARRAY['zh'], ARRAY['composed','professional','authoritative'], ARRAY['authoritative','professional'], ARRAY['customer_service','banking','enterprise_support'], 'limited', NULL, 'eleven_flash_v2_5', 0.70, 0.75, 0.95),
-- Japanese
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Yuki (JA)', 'Polite, professional Japanese female voice. Respectful keigo register. Essential for Japanese-market customer service.', 'female', 'young', 'Standard Japanese', ARRAY['ja'], ARRAY['polite','respectful','professional'], ARRAY['professional','warm'], ARRAY['customer_service','banking','telco'], 'limited', NULL, 'eleven_flash_v2_5', 0.70, 0.75, 0.95),
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Kenji (JA)', 'Measured, professional Japanese male voice. Formal register with natural warmth. Suitable for enterprise B2B.', 'male', 'middle_aged', 'Standard Japanese', ARRAY['ja'], ARRAY['measured','professional','formal'], ARRAY['authoritative','professional'], ARRAY['customer_service','enterprise_support','banking'], 'limited', NULL, 'eleven_flash_v2_5', 0.75, 0.75, 0.95),
-- Korean
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Jiyeon (KO)', 'Professional Korean female voice. Clear standard pronunciation. Suitable for financial services and telco.', 'female', 'young', 'Standard Korean', ARRAY['ko'], ARRAY['professional','clear','warm'], ARRAY['professional','warm'], ARRAY['customer_service','banking','telco'], 'moderate', NULL, 'eleven_flash_v2_5', 0.65, 0.75, 1.0),
-- Malay/Bahasa
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Nurul (MS)', 'Warm, professional Bahasa Malaysia/Indonesia female voice. Neutral accent suitable for both markets.', 'female', 'young', 'Standard Malay', ARRAY['ms'], ARRAY['warm','professional','clear'], ARRAY['warm','professional'], ARRAY['customer_service','banking','telco'], 'moderate', NULL, 'eleven_flash_v2_5', 0.65, 0.75, 1.0),
-- Italian
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'elevenlabs_premade', 'Giulia (IT)', 'Professional Italian female voice. Warm delivery with clear articulation. Suitable for premium consumer services.', 'female', 'young', 'Standard Italian', ARRAY['it'], ARRAY['warm','professional','clear'], ARRAY['warm','professional'], ARRAY['customer_service','banking','retail'], 'moderate', 'pqHfZKP75CvOlQylNhV4', 'eleven_flash_v2_5', 0.65, 0.75, 1.0),
-- Dutch
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Lotte (NL)', 'Professional Dutch female voice. Clear, efficient delivery. Suitable for Dutch and Belgian markets.', 'female', 'young', 'Standard Dutch', ARRAY['nl'], ARRAY['professional','clear','efficient'], ARRAY['professional','friendly'], ARRAY['customer_service','banking','insurance'], 'moderate', NULL, 'eleven_flash_v2_5', 0.65, 0.75, 1.0),
-- Turkish
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Zeynep (TR)', 'Warm Turkish female voice. Friendly, professional delivery. Well-suited for consumer-facing services.', 'female', 'young', 'Standard Turkish', ARRAY['tr'], ARRAY['warm','friendly','professional'], ARRAY['warm','friendly'], ARRAY['customer_service','telco','retail'], 'moderate', NULL, 'eleven_flash_v2_5', 0.65, 0.75, 1.0),
-- Polish
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Agnieszka (PL)', 'Professional Polish female voice. Clear diction with natural warmth. Ideal for CEE market contact centres.', 'female', 'young', 'Standard Polish', ARRAY['pl'], ARRAY['professional','clear','warm'], ARRAY['professional','warm'], ARRAY['customer_service','banking','bpo'], 'moderate', NULL, 'eleven_flash_v2_5', 0.65, 0.75, 1.0),
-- Swahili
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Amina (SW)', 'Professional Swahili female voice. Clear, warm delivery. Designed for East African market contact centres.', 'female', 'young', 'Standard Swahili', ARRAY['sw'], ARRAY['professional','warm','clear'], ARRAY['warm','professional'], ARRAY['customer_service','banking','telco'], 'moderate', NULL, 'eleven_flash_v2_5', 0.65, 0.75, 1.0),
-- Tagalog/Filipino
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Maria (TL)', 'Warm, professional Filipino female voice. Clear English-accented delivery suitable for BPO operations serving global markets.', 'female', 'young', 'Filipino', ARRAY['tl','en'], ARRAY['warm','professional','friendly'], ARRAY['warm','friendly'], ARRAY['customer_service','bpo','outsourcing'], 'moderate', NULL, 'eleven_flash_v2_5', 0.65, 0.75, 1.0),
-- Russian
(uuid_generate_v4(), NULL, true, 'elevenlabs', 'trustnow_designed', 'Natasha (RU)', 'Professional Russian female voice. Clear standard pronunciation. Suitable for CIS market customer service.', 'female', 'young', 'Standard Russian', ARRAY['ru'], ARRAY['professional','clear','composed'], ARRAY['professional','authoritative'], ARRAY['customer_service','banking','telco'], 'limited', NULL, 'eleven_flash_v2_5', 0.70, 0.75, 0.95);

-- ─── PIPER ON-PREMISE VOICES (Partition B) ────────────────────────────────
INSERT INTO voices (voice_id, tenant_id, is_global, provider, source_type, name, description, gender, language_tags, trait_tags, piper_model_file, stability_default, similarity_default, speed_default) VALUES
(uuid_generate_v4(), NULL, true, 'piper', 'piper_onprem', 'Lessac (EN-US, Piper)', 'On-premise English US female voice. Piper TTS — zero external API calls.', 'female', ARRAY['en'], ARRAY[]::text[], 'en_US-lessac-medium.onnx', 0.65, 0.75, 1.0),
(uuid_generate_v4(), NULL, true, 'piper', 'piper_onprem', 'LibriTTS (EN-US, Piper)', 'On-premise English US high-quality voice. Piper TTS — zero external API calls.', 'female', ARRAY['en'], ARRAY[]::text[], 'en_US-libritts_r-medium.onnx', 0.65, 0.75, 1.0),
(uuid_generate_v4(), NULL, true, 'piper', 'piper_onprem', 'DaveFX (ES, Piper)', 'On-premise Spanish male voice. Piper TTS — zero external API calls.', 'male', ARRAY['es'], ARRAY[]::text[], 'es_ES-davefx-medium.onnx', 0.65, 0.75, 1.0),
(uuid_generate_v4(), NULL, true, 'piper', 'piper_onprem', 'Siwis (FR, Piper)', 'On-premise French female voice. Piper TTS — zero external API calls.', 'female', ARRAY['fr'], ARRAY[]::text[], 'fr_FR-siwis-medium.onnx', 0.65, 0.75, 1.0),
(uuid_generate_v4(), NULL, true, 'piper', 'piper_onprem', 'Thorsten (DE, Piper)', 'On-premise German male voice. Piper TTS — zero external API calls.', 'male', ARRAY['de'], ARRAY[]::text[], 'de_DE-thorsten-medium.onnx', 0.65, 0.75, 1.0),
(uuid_generate_v4(), NULL, true, 'piper', 'piper_onprem', 'Paola (IT, Piper)', 'On-premise Italian female voice. Piper TTS — zero external API calls.', 'female', ARRAY['it'], ARRAY[]::text[], 'it_IT-paola-medium.onnx', 0.65, 0.75, 1.0),
(uuid_generate_v4(), NULL, true, 'piper', 'piper_onprem', 'Faber (PT-BR, Piper)', 'On-premise Brazilian Portuguese male voice. Piper TTS — zero external API calls.', 'male', ARRAY['pt'], ARRAY[]::text[], 'pt_BR-faber-medium.onnx', 0.65, 0.75, 1.0);
